create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    phone text,
    service text,
    message text,
    created_at timestamptz default now()
);

alter table public.contacts enable row level security;

drop policy if exists "service_role_all_access" on public.contacts;
create policy "service_role_all_access"
    on public.contacts
    for all
    to service_role
    using (true)
    with check (true);
